### ISSUE TITLE
set-env is no longer supported

### ISSUE THREAD

**Issue by Joseph-Duty-VA** [rajyraman/powerapps-deploy-solution#1]
I'm giving this action a try, but set-env now appears to be disabled, so it breaks (https://github.com/actions/toolkit/issues/641).  Any plans to update this action to eliminate reference?

**Comment by rajyraman** [comment]
@Joseph-Duty-VA - I am not setting any environment variables in this action. Can be please explain what this issue is, possibly with a screenshot?

**Comment by Joseph-Duty-VA** [comment]
sorry, i realized this is against the wrong action- i meant to post this to the extract solution, not the deploy solution.  I'll comment over there
